insert into city (id, name, country_id) values (1, 'Simenqian', 2);
insert into city (id, name, country_id) values (2, 'Kungsbacka', 6);
insert into city (id, name, country_id) values (3, 'Jati', 1);
insert into city (id, name, country_id) values (4, 'Bacnar', 8);
insert into city (id, name, country_id) values (5, 'Maria', 9);
insert into city (id, name, country_id) values (6, 'Aroa', 9);
insert into city (id, name, country_id) values (7, 'Siquanpu', 2);
insert into city (id, name, country_id) values (8, 'Xikou', 4);
insert into city (id, name, country_id) values (9, 'Svetogorsk', 7);
insert into city (id, name, country_id) values (10, 'Gaoyang', 5);
insert into city (id, name, country_id) values (11, 'Argotirto Krajan', 8);
insert into city (id, name, country_id) values (12, 'Krajan Tambakrejo', 7);
insert into city (id, name, country_id) values (13, 'San Lucas', 7);
insert into city (id, name, country_id) values (14, 'Corinto', 3);
insert into city (id, name, country_id) values (15, 'Wenquan', 3);

insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (1, 'Destruction of Brain, Percutaneous Approach', '24/4/2017', null, null, 2, 11);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (2, 'Supplement Right 3rd Toe with Autol Sub, Perc Endo Approach', '1/4/2018', null, null, 10, 29);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (3, 'Fusion of Right Metatarsal-Tarsal Joint, Perc Approach', '24/10/2017', null, null, 2, 20);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (4, 'Removal of Infusion Dev from L Carpal Jt, Perc Endo Approach', '27/5/2017', null, null, 13, 12);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (5, 'Removal of Synth Sub from R Carpal Jt, Perc Approach', '28/4/2017', 'Quillwort', '11/9/2017', 12, 4);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (6, 'Reattachment of Right Upper Leg Muscle, Perc Endo Approach', '25/7/2017', null, null, 5, 8);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (7, 'Beam Radiation of Right Breast using Electrons, Intraop', '13/5/2017', null, null, 14, 19);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (8, 'Extirpation of Matter from Lumbosacral Plexus, Perc Approach', '31/7/2017', null, null, 9, 19);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (9, 'Revision of Infusion Device in Fem Perineum, Extern Approach', '25/1/2018', null, null, 8, 29);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (10, 'Remove of Infusion Dev from Vas Deferens, Perc Endo Approach', '8/4/2017', 'European Privet', '19/4/2017', 7, 4);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (11, 'Repair Right Foot Muscle, Percutaneous Endoscopic Approach', '13/11/2017', null, null, 15, 9);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (12, 'Lower Veins, Excision', '5/2/2018', null, null, 9, 13);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (13, 'Fusion of Sacrococcygeal Jt with Nonaut Sub, Perc Approach', '1/1/2018', null, null, 7, 25);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (14, 'Supplement Pericardium with Autol Sub, Perc Approach', '5/8/2017', null, null, 13, 14);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (15, 'Extirpation of Matter from Intracran Art, Open Approach', '27/9/2017', 'Cuban Copperleaf', '5/10/2017', 15, 3);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (16, 'Drainage of Left Axilla with Drainage Device, Perc Approach', '25/6/2017', null, null, 13, 17);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (17, 'Supplement Inf Mesent Vein with Nonaut Sub, Perc Approach', '28/4/2017', null, null, 6, 4);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (18, 'Bypass 2 Cor Art from R Int Mammary w Zooplastic, Open', '5/2/2018', null, null, 7, 7);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (19, 'Supplement L Shoulder Bursa/Lig w Synth Sub, Perc Endo', '16/8/2017', null, null, 3, 6);
insert into comment (id, content, date, removed_reason, removed_date, post_id, author_id) values (20, 'Removal of Autol Sub from L Glenoid Cav, Open Approach', '2/11/2017', null, null, 9, 3);

insert into faculty (id, name, description, city_id, university_id) values (1, 'University of Nicosia', Aberystwyth
, 'Rosemary - Primerba, Paste', 9, 7);
insert into faculty (id, name, description, city_id, university_id) values (2, 'Southern Nazarene University', 'Pastry - Banana Tea Loaf', 12, 10);
insert into faculty (id, name, description, city_id, university_id) values (3, 'Universidad de Málaga', 'Flower - Commercial Bronze', 11, 8);
insert into faculty (id, name, description, city_id, university_id) values (4, 'Albion College', 'Bacardi Mojito', 14, 2);
insert into faculty (id, name, description, city_id, university_id) values (5, 'University of Virginia, College at Wise', 'V8 - Tropical Blend', 2, 14);
insert into faculty (id, name, description, city_id, university_id) values (6, 'Universidad Autónoma del Noreste', 'Extract - Rum', 7, 6);
insert into faculty (id, name, description, city_id, university_id) values (7, 'University of Kuopio', 'Flour - Chickpea', 2, 3);
insert into faculty (id, name, description, city_id, university_id) values (8, 'Newschool of Architecture and Design', 'Cinnamon - Stick', 3, 11);
insert into faculty (id, name, description, city_id, university_id) values (9, 'Saint Ferdinand College', 'Quail - Eggs, Fresh', 10, 11);
insert into faculty (id, name, description, city_id, university_id) values (10, 'Effat College', 'Extract - Almond', 13, 7);
insert into faculty (id, name, description, city_id, university_id) values (11, 'Skidmore College', 'Sauce - Bernaise, Mix', 15, 6);
insert into faculty (id, name, description, city_id, university_id) values (12, 'University of Zenica', 'Apple - Custard', 5, 3);
insert into faculty (id, name, description, city_id, university_id) values (13, 'Hogeschool West-Vlaanderen (TU)', 'Marzipan 50/50', 5, 1);
insert into faculty (id, name, description, city_id, university_id) values (14, 'Notre Dame de Namur University', 'Wine - Red, Marechal Foch', 2, 5);
insert into faculty (id, name, description, city_id, university_id) values (15, 'Effat College', 'Chambord Royal', 2, 3);
insert into faculty (id, name, description, city_id, university_id) values (16, 'Fontbonne College', 'Veal - Round, Eye Of', 2, 2);
insert into faculty (id, name, description, city_id, university_id) values (17, 'Rochester Institute of Technology', 'Figs', 10, 14);
insert into faculty (id, name, description, city_id, university_id) values (18, 'Universidad Nacional de Asunción', 'Peach - Fresh', 4, 14);
insert into faculty (id, name, description, city_id, university_id) values (19, 'Carthage College', 'Beef - Tenderloin Tails', 6, 10);
insert into faculty (id, name, description, city_id, university_id) values (20, 'Centre Universitaire de Technologie', 'Dried Peach', 9, 1);

insert into flag_comment (flagger_id, comment_id, reason, date, archived) values (5, 12, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', '23/5/2017', true);
insert into flag_comment (flagger_id, comment_id, reason, date, archived) values (9, 3, 'Vestibulum justo.', '23/5/2017', true);
insert into flag_comment (flagger_id, comment_id, reason, date, archived) values (2, 11, 'Lorem rhoncus.', '23/5/2017', false);
insert into flag_comment (flagger_id, comment_id, reason, date, archived) values (8, 6, 'In tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '23/5/2017', true);
insert into flag_comment (flagger_id, comment_id, reason, date, archived) values (9, 7, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '23/5/2017', false);

insert into flag_post (flagger_id, post_id, reason, date, archived) values (11, 4, 'Universal clear-thinking process improvement', '16/6/2017', false);
insert into flag_post (flagger_id, post_id, reason, date, archived) values (6, 11, 'Optional bandwidth-monitored flexibility', '3/9/2017', true);
insert into flag_post (flagger_id, post_id, reason, date, archived) values (8, 12, 'Automated foreground customer loyalty', '16/7/2017', true);
insert into flag_post (flagger_id, post_id, reason, date, archived) values (27, 4, 'Triple-buffered clear-thinking hub', '13/7/2017', false);
insert into flag_post (flagger_id, post_id, reason, date, archived) values (17, 7, 'Fundamental full-range superstructure', '25/7/2017', true);

insert into flag_user (flagger_id, flagged_id, reason, date, archived) values (6, 12, 'Exclusive reciprocal emulation', '14/1/2018', false);
insert into flag_user (flagger_id, flagged_id, reason, date, archived) values (25, 8, 'De-engineered grid-enabled data-warehouse', '27/4/2017', true);
insert into flag_user (flagger_id, flagged_id, reason, date, archived) values (16, 7, 'Quality-focused impactful support', '18/11/2017', false);
insert into flag_user (flagger_id, flagged_id, reason, date, archived) values (9, 14, 'Up-sized analyzing function', '8/7/2017', true);
insert into flag_user (flagger_id, flagged_id, reason, date, archived) values (1, 14, 'User-centric foreground forecast', '17/11/2017', false);

insert into following (follower_id, followed_id, date) values (4, 7, '4/5/2017');
insert into following (follower_id, followed_id, date) values (3, 14, '19/9/2017');
insert into following (follower_id, followed_id, date) values (4, 8, '28/8/2017');
insert into following (follower_id, followed_id, date) values (9, 5, '11/3/2018');
insert into following (follower_id, followed_id, date) values (1, 6, '11/4/2017');
insert into following (follower_id, followed_id, date) values (11, 12, '27/1/2018');
insert into following (follower_id, followed_id, date) values (24, 14, '14/11/2017');
insert into following (follower_id, followed_id, date) values (29, 14, '16/5/2017');
insert into following (follower_id, followed_id, date) values (15, 3, '11/8/2017');
insert into following (follower_id, followed_id, date) values (24, 11, '23/5/2017');
insert into following (follower_id, followed_id, date) values (25, 7, '12/4/2017');
insert into following (follower_id, followed_id, date) values (14, 13, '9/1/2018');
insert into following (follower_id, followed_id, date) values (27, 6, '27/9/2017');
insert into following (follower_id, followed_id, date) values (25, 8, '21/10/2017');
insert into following (follower_id, followed_id, date) values (11, 6, '8/5/2017');
insert into following (follower_id, followed_id, date) values (1, 13, '10/5/2017');
insert into following (follower_id, followed_id, date) values (19, 3, '24/1/2018');
insert into following (follower_id, followed_id, date) values (14, 15, '24/8/2017');
insert into following (follower_id, followed_id, date) values (17, 13, '31/3/2018');
insert into following (follower_id, followed_id, date) values (25, 12, '16/5/2017');
insert into following (follower_id, followed_id, date) values (1, 7, '7/9/2017');
insert into following (follower_id, followed_id, date) values (14, 8, '8/7/2017');
insert into following (follower_id, followed_id, date) values (8, 14, '21/5/2017');
insert into following (follower_id, followed_id, date) values (11, 3, '9/10/2017');
insert into following (follower_id, followed_id, date) values (14, 1, '16/9/2017');
insert into following (follower_id, followed_id, date) values (6, 5, '27/1/2018');
insert into following (follower_id, followed_id, date) values (29, 5, '23/4/2017');
insert into following (follower_id, followed_id, date) values (23, 14, '21/7/2017');
insert into following (follower_id, followed_id, date) values (1, 6, '5/9/2017');
insert into following (follower_id, followed_id, date) values (14, 14, '1/4/2018');



insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (1, 'aavrahm0@vistaprint.com', 'aavrahm0', '12/4/2001', '1KWYxNbXoZ4wxeKTVviejTyoyYZSPEYVjh', 'Annabella Avrahm', '22/6/2017', 'Decreased fetal movements, unspecified trimester, fetus 3', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (2, 'bgiorgioni1@about.me', 'bgiorgioni1', '1/3/2002', '1FhDGAyHvEyoEDD8DvXSArpV4Doud3J5Qj', 'Broddie Giorgioni', '1/1/2018', 'Motorcycle passenger injured in collision with pedestrian or animal in nontraffic accident', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (3, 'apanks2@jigsy.com', 'apanks2', '9/6/1997', '1NisuEkTYnQH6pvm6YE5RbxpfbF7JJ82x7', 'Anton Panks', '7/9/2017', 'Unspecified balloon accident injuring occupant', 'banned');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (4, 'dmatyatin3@google.com.br', 'dmatyatin3', '11/4/2000', '1K2NT9iZ7LnDDei5Dbm7XT9Z3L6bHqVPFj', 'Dian Matyatin', '8/10/2017', 'Displaced unspecified condyle fracture of lower end of right femur, subsequent encounter for closed fracture with routine healing', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (5, 'mbullin4@liveinternet.ru', 'mbullin4', '2/4/1999', '1MwQBTE5yZffoNCHfEnkADzrpzqJuVSjzk', 'Malvina Bullin', '2/10/2018', 'Malignant carcinoid tumor of the transverse colon', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (6, 'kbalderston5@smugmug.com', 'kbalderston5', '7/6/1997', '1HaS94fMSDSnY4KCzXVC92iE912sQvLgUv', 'Klement Balderston', '7/9/2017', 'Occupant of animal-drawn vehicle injured in collision with other animal-drawn vehicle', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (7, 'swinsom6@gmpg.org', 'swinsom6', '1/2/1997', '1GZXQTaXSdM3v99vA6Bx4SpcKAXgVs8bxx', 'Simmonds Winsom', '9/8/2017', 'Other hang-glider accident injuring occupant', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (8, 'abirckmann7@nyu.edu', 'abirckmann7', '5/8/1998', '1PGUCjB4rMH29H8MJGP5MJTembgVpk9tJT', 'Ashlie Birckmann', '8/3/2017', 'Candidiasis of skin and nail', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (9, 'lleverton8@sogou.com', 'lleverton8', '2/2/1994', '153JtWhmnVTp6DVcfQ5g7v9AHVDe7KMufi', 'Lucho Leverton', '5/8/2017', 'Disproportion of reconstructed breast', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (10, 'imc9@privacy.gov.au', 'imc9', '3/1/1992', '1GezVUHiKoJRwnPhn4kyd1ehZG4thSMUjD', 'Isaiah Mc Queen', '11/7/2017', 'Other injury of heart with hemopericardium, subsequent encounter', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (11, 'spetrova@networkadvertising.org', 'spetrova', '5/5/2000', '1ewrTL9Fy7ZQnT1XhpzUsR2EjYVXbRxup', 'Simon Petrov', '6/10/2017', 'Displaced fracture of neck of right radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (12, 'fskamellb@upenn.edu', 'fskamellb', '11/6/1993', '1AKxqEHzJ63F3KUaE5TQSLjnv8EJrPPCKZ', 'Fernandina Skamell', '6/4/2017', 'Hemopericardium as current complication following acute myocardial infarction', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (13, 'ibrayshayc@naver.com', 'ibrayshayc', '10/5/1993', '1Lw9okg3FzuhSd5sm9BppD6dKyBfPGBZjv', 'Itch Brayshay', '2/4/2018', 'Laceration of superficial palmar arch of right hand, initial encounter', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (14, 'omauchlined@independent.co.uk', 'omauchlined', '7/1/1994', '134VFRP2Vz7D1ZjYDDJHZRD53pBNcFyc1U', 'Oona Mauchline', '3/4/2018', 'Toxic effect of contact with other venomous fish, accidental (unintentional), initial encounter', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (15, 'hkendelle@surveymonkey.com', 'hkendelle', '4/2/1999', '16wQ8A8uQES4YyG2VSfHETmXD6fDrLhiX5', 'Hersh Kendell', '7/2/2017', 'Burn of first degree of shoulder and upper limb, except wrist and hand, unspecified site, subsequent encounter', 'admin');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (16, 'jthiemef@marriott.com', 'jthiemef', '10/6/2001', '1Hkc9K3GMbv1fCWeUzCzjPmYk6js4A8MTY', 'Junette Thieme', '7/3/2017', 'Personal history of malignant neoplasm of thyroid', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (17, 'gscareg@usda.gov', 'gscareg', '4/2/1998', '1LrpE7gTSL7UastHaTuvhN2hePFDDXWaVa', 'Garrek Scare', '12/6/2017', 'Acute eczematoid otitis externa, right ear', 'banned');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (18, 'sivashechkinh@sourceforge.net', 'sivashechkinh', '10/1/1994', '1EbVnA79QzKCk73n8FBjVVbVQp7ofGvuiD', 'Stephenie Ivashechkin', '6/2/2017', 'Injury of radial nerve at upper arm level, left arm, subsequent encounter', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (19, 'eseversi@nhs.uk', 'eseversi', '12/11/1993', '1CKST64UrNq9ZLbYzMJXEctcjT3mGmRMEn', 'Estel Severs', '6/5/2017', 'Encounter for initial prescription of vaginal ring hormonal contraceptive', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (20, 'ajuettj@abc.net.au', 'ajuettj', '12/1/1995', '1Ks2xfaDhWStPr2kKb4rYseipYHaovVpwh', 'Artus Juett', '9/6/2017', 'Labor and delivery complicated by other cord entanglement, with compression, fetus 2', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (21, 'afindenk@phoca.cz', 'afindenk', '16/7/1996', '1Ks9a7QeQmn572Nr2mvKfEf4ubzxM4xBuh', 'Addie Finden', '1/2/2018', 'Activities involving ice and snow', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (22, 'pbirkl@disqus.com', 'pbirkl', '27/9/2000', '1G3TZheGQZx2hRv42jC4VSpC6uNGBWzem5', 'Penelope Birk', '4/2/2017', 'Postprocedural subglottic stenosis', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (23, 'sfarmarm@miitbeian.gov.cn', 'sfarmarm', '7/7/1997', '1BqNSxNmoTxje6gNJT1qgEyyaBs3DpMahC', 'Seward Farmar', '10/1/2017', 'Aneurysmal bone cyst', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (24, 'bsaizn@biblegateway.com', 'bsaizn', '12/11/1995', '12DYK9shjrKmsj9PHtmLiLoJQG5b4McDv7', 'Bili Saiz', '9/6/2017', 'Pathological fracture in neoplastic disease, right foot, subsequent encounter for fracture with routine healing', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (25, 'agowrieo@mediafire.com', 'agowrieo', '18/11/1998', '12VKGyy4QSEo68Z7Akmr6E5wNXJRTox9wU', 'Abby Gowrie', '5/12/2017', 'Displaced Maisonneuve''s fracture of unspecified leg, subsequent encounter for closed fracture with routine healing', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (26, 'jkendredp@rambler.ru', 'jkendredp', '3/16/2002', '12HFxevVcxRCdEF8sVRgpYU52Dvcttt2NR', 'Janith Kendred', '5/2/2018', 'Adverse effect of saline and osmotic laxatives', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (27, 'mcapelleq@tripadvisor.com', 'mcapelleq', '9/4/1999', '16kPRPFE6CB5CFXRTDTcgcJuDWPzrwB7W6', 'Mord Capelle', '3/1/2018', 'Nondisplaced transverse fracture of shaft of right fibula, subsequent encounter for open fracture type I or II with nonunion', 'banned');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (28, 'kdavissonr@networksolutions.com', 'kdavissonr', '30/3/1992', '1FqxiBLaAEgmSzU2Enm8ET26NsAbjbyySf', 'Katerina Davisson', '2/1/2018', 'Burn of unspecified degree of right scapular region, sequela', 'active');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (29, 'hmansers@cpanel.net', 'hmansers', '26/2/1999', '1MJt5cbRegPeZ8LFPVvraaZ39VxstmbRRN', 'Hedi Manser', '5/2/2017', 'Pneumonia due to staphylococcus, unspecified', 'banned');
insert into user (id, email, username, birthdate, password, name, register_date, description, type) values (30, 'mcominottit@example.com', 'mcominottit', '11/29/1991', '1wibWX46UH7AFxSPDuBUXmr83bdiJFv85', 'Marmaduke Cominotti', '4/6/2017', 'Minor laceration of vertebral artery', 'active');

